updated dotfiles

diff --git a/bin/dot b/bin/dot
--- a/bin/dot
+++ b/bin/dot
@@ -5,40 +5,55 @@ DOTDIR=~/dotfiles
 
 # dispatch subcommands
 case "$1" in
-  restow)
-    shift
-    if [[ $# -eq 0 ]]; then
-      echo "❗ Usage: dot restow <package> [package...]"
-      exit
-    fi
-    for pkg in "$@"; do
-      echo "↻ Restowing $pkg..."
-      if stow -d "$DOTDIR" -R "$pkg"; then
-        echo "✅ Done"
-      else
-        echo "❌ Failed to restow $pkg"
-      fi
-    done
-    ;;
-  bundle)
-    antidote bundle < ~/.config/zsh/.zsh_plugins.txt > ~/.config/zsh/.zsh_plugins.zsh
-    echo "✅ Plugins bundled"
-    ;;
-  list)
-    echo "dotfile packages:"
-    find "$DOTDIR" -mindepth 1 -maxdepth 1 -type d \
-      ! -name ".git" \
-      ! -name "bin" \
-      ! -name ".github" \
-      -exec basename {} \;
-    ;;
-  push)
-    git -C "$DOTDIR" add .
-    git -C "$DOTDIR" commit -m "updated dotfiles"
-    git -C "$DOTDIR" push && echo "✅ dotfiles pushed"
-    ;;
-  *)
-    echo "Usage: dot {restow|bundle|list|push}"
-    ;;
-esac
+restow)
+	shift
+	if [[ $# -eq 0 ]]; then
+		echo "❗ Usage: dot restow <package> [package...]"
+		exit
+	fi
+	for pkg in "$@"; do
+		echo "↻ Restowing $pkg..."
+		if stow -d "$DOTDIR" -R "$pkg"; then
+			echo "✅ Done"
+		else
+			echo "❌ Failed to restow $pkg"
+		fi
+	done
+	;;
+bundle)
+	antidote bundle <~/.config/zsh/.zsh_plugins.txt >~/.config/zsh/.zsh_plugins.zsh
+	echo "✅ Plugins bundled"
+	;;
+list)
+	echo "dotfile packages:"
+	find "$DOTDIR" -mindepth 1 -maxdepth 1 -type d \
+		! -name ".git" \
+		! -name "bin" \
+		! -name ".github" \
+		-exec basename {} \;
+	;;
+edit)
+	if [[ $# -ne 2 ]]; then
+		echo "❗ Usage: dot edit <package>"
+		exit 1
+	fi
 
+	pkg="$2"
+	target="$DOTDIR/$pkg"
+
+	if [[ ! -d "$target" ]]; then
+		echo "❌ No such package: $pkg"
+		exit 1
+	fi
+
+	cd "$target" && nvim
+	;;
+push)
+	git -C "$DOTDIR" add .
+	git -C "$DOTDIR" commit -m "updated dotfiles"
+	git -C "$DOTDIR" push && echo "✅ dotfiles pushed"
+	;;
+*)
+	echo "Usage: dot {restow|bundle|list|push}"
+	;;
+esac
